// Server project projection plus short-lived pointer drafts; no browser song bank.
(function(){
  var rows=[],sig='',paint=null,drafts={},base=null,gesture=null,dirty=false,lastStep=-1,wheelTimer=null,nameBase=null;
  function p(){return AbxProject.project();}
  function row(id){return rows.find(function(r){return r.t.id===id;});}
  function sync(){if(!p()||paint||dirty||AbxProject.group()||document.activeElement&&document.activeElement.classList&&document.activeElement.classList.contains('seqname'))return;var next=p().id+':'+p().revision+':'+(Abx.state().workspace||{}).selectedSceneId;if(next===sig)return;sig=next;
    rows=p().tracks.map(function(t){var c=AbxProject.clip(t);return {t:t,c:c,a:c&&c.kind==='steps'&&p().assets.find(function(a){return a.id===c.assetId;})};});
    if(document.getElementById('seqwrap').style.display==='block'){render();patRender();}}
  function padBg(slot,v){return Abx.color.chanA(slot,0.32+0.5*Math.min(1,v/1.5));}
  function render(){var h='<div class="seqruler"><span class="rlead"></span><span class="rpads">';
    for(var i=0;i<16;i++)h+='<span class="rstep'+(i%4===0?' beat':'')+'">'+(i%4===0?i/4+1:'')+'</span>';h+='</span><span class="rtrail"></span></div>';
    rows.forEach(function(r){var t=r.t,c=r.c,k='d'+t.slot,visual=c&&c.kind==='steps';
      h+='<div class="seqrow" data-track="'+t.id+'" style="--rc:'+Abx.color.chan(k)+'"><span class="seqgrip" data-track="'+t.id+'" draggable="true" title="drag to reorder">☰</span>';
      h+='<input class="seqname" data-track="'+t.id+'" value="'+Abx.esc(r.a?r.a.name+(r.a.index?':'+r.a.index:''):t.name)+'"'+(!visual?' disabled':'')+' title="sample name"><span class="seqtag">'+(visual?'steps':c?'code':'inactive')+'</span>';
      h+='<span class="seqctl"><button data-seq="mute" data-track="'+t.id+'" class="'+(t.mixer.mute?'on':'')+'">M</button><button data-seq="clear" data-track="'+t.id+'" title="clear rhythm">&times;</button><button data-seq="delete" data-track="'+t.id+'" title="delete track">−</button></span><span class="seqslot">'+k+'</span><div class="seqpads">';
      if(visual)c.steps.forEach(function(v,s){h+='<span class="pad'+(v>0?' on':'')+(s%4===0?' beat':'')+'" data-track="'+t.id+'" data-step="'+s+'"'+(v>0?' style="background:'+padBg(k,v)+'"':'')+'></span>';});else h+='<span class="seqhint">'+(c?'Edit code in console':'Choose a scene or add a clip')+'</span>';
      h+='</div><input type="range" class="seqvol" data-seqvol="'+t.id+'" min="0" max="2" step="0.05" value="'+t.mixer.level+'"'+(t.channel===null?' disabled':'')+' title="channel volume"></div>';});
    document.getElementById('seqrows').innerHTML=h;var first=rows.find(function(r){return r.c&&r.c.kind==='steps';});document.getElementById('seqSwing').value=first?first.c.swing*100:0;document.getElementById('seqSwingV').textContent=first?first.c.swing*100:0;}
  function setPad(id,step,value){var r=row(id);if(!r||!r.c||r.c.kind!=='steps')return;if(!base){base={id:p().id,revision:p().revision};gesture=crypto.randomUUID();}if(!drafts[r.c.id])drafts[r.c.id]=r.c.steps.slice();drafts[r.c.id][step]=value;dirty=true;
    var el=document.querySelector('.pad[data-track="'+id+'"][data-step="'+step+'"]');if(el){el.classList.toggle('on',value>0);el.style.background=value>0?padBg('d'+r.t.slot,value):'';}}
  function flushPending(){if(paint||!dirty)return;var edits=Object.keys(drafts).map(function(id){return {type:'steps.set',clipId:id,steps:drafts[id]};}),b=base,g=gesture;drafts={};base=null;gesture=null;dirty=false;
    return AbxProject.edit(edits,'Paint rhythm',g,b).then(function(j){sig='';sync();if(j.ok&&!Abx.stopping()&&Abx.state().status==='idle'&&!Abx.state().stopped)Abx.send({cmd:'resume'});});}
  function beforeStop(){paint=null;clearTimeout(wheelTimer);flushPending();}
  function patRender(){if(!p())return;var selected=p().scenes.find(function(s){return s.id===(Abx.state().workspace||{}).selectedSceneId;}),h='';p().sceneOrder.forEach(function(id){var s=p().scenes.find(function(s){return s.id===id;}),filled=Object.values(s.clips).some(function(id){var c=p().clips.find(function(c){return c.id===id;});return c&&(c.kind==='code'||c.steps.some(function(v){return v>0;}));});h+='<button class="patslot'+(selected&&selected.id===id?' on':'')+(filled?' filled':'')+'" data-pat="'+id+'">'+Abx.esc(s.name)+'</button>';});document.getElementById('patslots').innerHTML=h;
    if(document.activeElement!==document.getElementById('songChain'))document.getElementById('songChain').value=p().arrangement.map(function(e){return p().scenes.find(function(s){return s.id===e.sceneId;}).name;}).join(' ');var on=Abx.state().projectRuntime&&Abx.state().projectRuntime.song,b=document.getElementById('songBtn');if(b){b.classList.toggle('on',!!on);b.textContent=on?'■ Song':'▶ Song';}}
  function selectPat(id){beforeStop();var s=p().scenes.find(function(s){return s.id===id;}),edits=[],refs=Object.assign({},s.clips);p().tracks.forEach(function(t){if(refs[t.id])return;var c=AbxProject.clip(t);if(c&&c.kind==='steps'){var copy=JSON.parse(JSON.stringify(c));copy.id=crypto.randomUUID();copy.name=s.name;copy.steps=copy.steps.map(function(){return 0;});edits.push({type:'clip.put',clip:copy});refs[t.id]=copy.id;}});edits.push({type:'scene.put',scene:{id:s.id,name:s.name,clips:refs}},{type:'scene.activate',sceneId:id});AbxProject.edit(edits,'Select scene '+s.name).then(function(){sig='';sync();});}
  function openSteps(){var w=document.getElementById('seqwrap');if(w.style.display==='block'){w.style.display='none';return;}['samplewrap','cheatwrap','curvewrap'].forEach(function(id){document.getElementById(id).style.display='none';});w.style.display='block';sig='';sync();}
  function entries(raw){return raw.trim().split(/\s+/).filter(Boolean).map(function(name){var s=p().scenes.find(function(s){return s.name.toUpperCase()===name.toUpperCase();});if(!s)throw new Error('Unknown scene '+name);return {id:crypto.randomUUID(),sceneId:s.id,cycles:1};});}
  function handleClick(b){var id=b.dataset.track,r=id&&row(id);
    if(b.dataset.act==='steps'){openSteps();return true;}if(b.dataset.pat){selectPat(b.dataset.pat);return true;}if(b.dataset.act==='seqadd'){AbxProject.newTrack('perc');return true;}
    if(b.dataset.act==='seqclear'){AbxProject.edit(rows.filter(function(r){return r.c&&r.c.kind==='steps';}).map(function(r){return {type:'steps.set',clipId:r.c.id,steps:r.c.steps.map(function(){return 0;})};}),'Clear scene rhythm');return true;}
    if(b.dataset.seq==='mute'){AbxProject.edit([{type:'mixer.set',trackId:id,values:{mute:!r.t.mixer.mute}}],'Mute channel');return true;}
    if(b.dataset.seq==='clear'&&r.c&&r.c.kind==='steps'){AbxProject.edit([{type:'steps.set',clipId:r.c.id,steps:r.c.steps.map(function(){return 0;})}],'Clear rhythm');return true;}
    if(b.dataset.seq==='delete'){AbxProject.edit([{type:'track.delete',trackId:id}],'Delete track');return true;}
    if(b.dataset.act==='songtoggle'){if(Abx.state().projectRuntime&&Abx.state().projectRuntime.song){Abx.send({cmd:'song.stop'});return true;}try{var es=entries(document.getElementById('songChain').value);if(!es.length)es=[{id:crypto.randomUUID(),sceneId:AbxProject.scene().id,cycles:1}];AbxProject.edit([{type:'arrangement.set',entries:es}],'Song chain').then(function(j){if(j.ok)Abx.send({cmd:'song.start'});});}catch(e){Abx.report({ok:false,error:e.message});}return true;}return false;}
  function handleInput(e){var el=e.target;if(el.classList&&el.classList.contains('seqname'))return true;
    if(el.dataset.seqvol!==undefined){AbxProject.edit([{type:'mixer.set',trackId:el.dataset.seqvol,values:{level:+el.value}}],'Channel volume');return true;}
    if(el.id==='seqSwing'){document.getElementById('seqSwingV').textContent=el.value;AbxProject.edit(rows.filter(function(r){return r.c&&r.c.kind==='steps';}).map(function(r){return {type:'swing.set',clipId:r.c.id,value:+el.value/100};}),'Swing');return true;}return false;}
  function replaceSound(id,name,editBase){var r=row(id);if(!r||!r.c||r.c.kind!=='steps')return;try{var a=AbxProject.asset(name);AbxProject.edit([{type:'asset.put',asset:a},{type:'sound.set',clipId:r.c.id,assetId:a.id}],'Replace sound',undefined,editBase);}catch(e){Abx.report({ok:false,error:e.message});}}
  document.addEventListener('focusin',function(e){if(e.target.classList&&e.target.classList.contains('seqname'))nameBase={id:p().id,revision:p().revision};});
  document.addEventListener('change',function(e){var el=e.target;if(el.classList&&el.classList.contains('seqname'))replaceSound(el.dataset.track,el.value.trim(),nameBase);nameBase=null;if(el.id==='songChain'){try{AbxProject.edit([{type:'arrangement.set',entries:entries(el.value)}],'Song chain');}catch(err){Abx.report({ok:false,error:err.message});}}});
  document.addEventListener('pointerdown',function(e){var pad=e.target.closest&&e.target.closest('.pad');if(!pad||e.button!==0)return;var r=row(pad.dataset.track),i=+pad.dataset.step;paint={on:!(r.c.steps[i]>0)};setPad(r.t.id,i,paint.on?1:0);e.preventDefault();});
  document.addEventListener('pointerover',function(e){if(!paint)return;var pad=e.target.closest&&e.target.closest('.pad');if(pad)setPad(pad.dataset.track,+pad.dataset.step,paint.on?1:0);});
  function end(){if(paint){paint=null;flushPending();}}document.addEventListener('pointerup',end);document.addEventListener('pointercancel',end);
  document.addEventListener('contextmenu',function(e){var pad=e.target.closest&&e.target.closest('.pad');if(pad){e.preventDefault();setPad(pad.dataset.track,+pad.dataset.step,0);flushPending();}});
  document.addEventListener('wheel',function(e){var pad=e.target.closest&&e.target.closest('.pad');if(!pad)return;var r=row(pad.dataset.track),i=+pad.dataset.step,v=(drafts[r.c.id]||r.c.steps)[i];if(!v)return;e.preventDefault();setPad(r.t.id,i,+Math.max(0.1,Math.min(1.5,v+(e.deltaY<0?0.1:-0.1))).toFixed(2));clearTimeout(wheelTimer);wheelTimer=setTimeout(flushPending,180);},{passive:false});
  document.addEventListener('dragstart',function(e){var chip=e.target.closest&&e.target.closest('.chip'),grip=e.target.closest&&e.target.closest('.seqgrip');if(chip)e.dataTransfer.setData('text/sample',chip.dataset.sample);else if(grip)e.dataTransfer.setData('text/track',grip.dataset.track);});
  document.addEventListener('dragover',function(e){if(e.target.closest&&e.target.closest('.seqrow'))e.preventDefault();});
  document.addEventListener('drop',function(e){var el=e.target.closest&&e.target.closest('.seqrow');if(!el)return;e.preventDefault();var sample=e.dataTransfer.getData('text/sample'),from=e.dataTransfer.getData('text/track');if(sample)replaceSound(el.dataset.track,sample);else if(from){var ids=p().tracks.map(function(t){return t.id;}),i=ids.indexOf(from),j=ids.indexOf(el.dataset.track);if(i>=0&&j>=0){ids.splice(i,1);ids.splice(j,0,from);AbxProject.edit([{type:'track.order',ids:ids}],'Reorder tracks');}}});
  function renderPlayhead(phase,playing){var step=playing?Math.floor(phase*16)%16:-1;if(step===lastStep)return;document.querySelectorAll('.pad.now').forEach(function(el){el.classList.remove('now');});if(step>=0)document.querySelectorAll('.pad[data-step="'+step+'"]').forEach(function(el){el.classList.add('now');});lastStep=step;}
  window.AbxSeq={sync:sync,openSteps:openSteps,handleClick:handleClick,handleInput:handleInput,flushPending:flushPending,beforeStop:beforeStop,renderPlayhead:renderPlayhead,songAdvance:function(){},seedDemo:function(){}};
})();
